name: tiktok_flutter

description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  #FLUTTER_SDK
  flutter:
    sdk: flutter
  #UI
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.6
  #FIREBASE
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.5
  #DEPENDENCIES_INJECTION (DI)
  get_it: ^7.7.0
  #STATE_MANAGEMENT
  stacked: ^3.4.2
  stacked_services: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  stacked_generator:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg