// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkklQjLGNqD8u36elfDVSyGBnGAfByX1M',
    appId: '1:1018933586485:web:bb44750755fc34186ddf7c',
    messagingSenderId: '1018933586485',
    projectId: 'tiktok-flutter-9b823',
    authDomain: 'tiktok-flutter-9b823.firebaseapp.com',
    storageBucket: 'tiktok-flutter-9b823.appspot.com',
    measurementId: 'G-9HVC6C5KDC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVf13Rzbcoem7_W0Tk_wrOFZJf3LSfP7k',
    appId: '1:1018933586485:android:3e25b151a06e977f6ddf7c',
    messagingSenderId: '1018933586485',
    projectId: 'tiktok-flutter-9b823',
    storageBucket: 'tiktok-flutter-9b823.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAE5gXl-a_1gNrIRzvMVoHpTNVToLFraIw',
    appId: '1:1018933586485:ios:af816f168b8d79c26ddf7c',
    messagingSenderId: '1018933586485',
    projectId: 'tiktok-flutter-9b823',
    storageBucket: 'tiktok-flutter-9b823.appspot.com',
    iosBundleId: 'com.example.tiktokFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAE5gXl-a_1gNrIRzvMVoHpTNVToLFraIw',
    appId: '1:1018933586485:ios:af816f168b8d79c26ddf7c',
    messagingSenderId: '1018933586485',
    projectId: 'tiktok-flutter-9b823',
    storageBucket: 'tiktok-flutter-9b823.appspot.com',
    iosBundleId: 'com.example.tiktokFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkklQjLGNqD8u36elfDVSyGBnGAfByX1M',
    appId: '1:1018933586485:web:6ee2b48a24903a646ddf7c',
    messagingSenderId: '1018933586485',
    projectId: 'tiktok-flutter-9b823',
    authDomain: 'tiktok-flutter-9b823.firebaseapp.com',
    storageBucket: 'tiktok-flutter-9b823.appspot.com',
    measurementId: 'G-FX4C9EHBB5',
  );
}
